default: &default
  adapter: postgresql

development:
  <<: *default
  # database: cardology_production_copy
  database: bubble_development

test:
  <<: *default
  database: bubble_test

production:
  <<: *default
  database: bubble_production  